travis:
  secure:
    BINSTAR_TOKEN: AhskuqaIWu5Yk0yKH1mDWaDsQwWWmtiLYou440g/CQsZ+Gqt4hIcETH+zlFM11oIgjs/NSu53tWDwIlW7MlhPFAFmh0S3d4aqOc+KSUqI1lDgsCIT17yrRGkFGsYyOQ7t1GcqiXatxWchJNZSJzTGL6iKKgExSBGGx5drHB/GJsY9ESnaOIgETbH7oCYCaT9o23s7dJm3PLE4Wbiv/lh9/pgxw72Njgj0GasigSqmL5NxqYrW8Oiisjd2ekKdkxDdz9eOfRbh5vjLOLj6DYvsbkQOSR+uAU8O+UumeiyCqL6YObwwoN0nPjNqmbakH+KDRgneEpX0o8ls8Yt+qlIAGeAY2y8UsOydKaba0JnSOczHG/pdlbZ3Z/K6It1t5L5cfgp0rT52pNoDUlbZt9vPHm3d/VMYhIDs9szRm6cGNOtEyr4LpayH0kzD0cxQxFJMhJf0KA0/KHblX0VJoQqu2G5aa1OMuNMe/sraMe0fCv/kfi5x07+gUZRHfJJNGQpfGsg/Q+x2VR6cOw0K4c1ZvgZKldLpQ10QAtqNY+9DwBDsCKZGJGV+jSLpMc2/V3RbejpTvLGGmhHqpjW6SbPEsoP0nAq4/IPWJhfw6ounF2w35OiIM20MtOjjpN958lVFay1R85IcWtiFQ/RgUC4q4/3ydLzNfvRJHyc9zQlJmc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
