travis:
  secure:
    BINSTAR_TOKEN: UjTofB/v+D01lC7/mleYtIJK0AqC7DwY30GqJf4+ukqnCACYBRjLUFdnRU0eGCEi9VoTVXZySjNeddzCe1XBIiaM5TNQlISf8NJcpj8RV79sUUtn9MYOwStgxHaMH9DOzkkUYRO44iH0Qlk5OF1ptbpY54QLWCS5RZ6E9j/Hw1JI17GgVO4KB9cyImoj0Pjn1pfLBQaBjeBuU5IZaFsdslllOaArch0C7ldMyi8Wb+I5mZRmhdsC+ItXc5JXrsa4C04D+RCMGNnK0SBcYDOvEgp6EM1AJ/FnmW6fRhizfRTJ7xVC6obaYWJv+jVzd6c3pmq5RXtzT2aSA5ng07uwJkZHrkFYKsGF9UfE+qzI90Zlr8dT0bQQmEbyoSNWGDvmXgI819hP/sw3YdO3ZDgb+IizlDk5hbZyHiFn6wgo8gC7mx0QY9qelYPPGpZzuUyx4wLoXV5ZwwEHLsMuX3SwePq/RO18WMJJVESUqoAHYMynN24O85xGnLE1IkqLENHcgwLq3g9AIo+/tV7pYOVuEC4ywpCros+E8W/9Pz6q6Z2Ic9AB2Kqx893GqZpRDHEl/Zw4fr3S+tsKShbTYqY3ILA8mZqrq1aCLZJbCYGYlO1vYflNFcdFJ1iFXXlhymHjw8HmhEuazaKPGT3FDLZdLpEDfna4MB1okACQGJMe/Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
